{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "aws-privateca-issuer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-privateca-issuer.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "aws-privateca-issuer.selectorLabels" . | nindent 6 }}
  {{- if hasKey .Values.pdb "minAvailable" }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  {{- if hasKey .Values.pdb "maxUnavailable" }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- end }}
{{- end }}
